### ISSUE TITLE
モバイル画面対応

### ISSUE THREAD

**Issue by Akira-Isegawa** [minmeeting/Documents#145]
ネイティブアプリは別途作るとして、ブラウザ版でモバイルからも使えるようにするか。

# ToDo
タイムライン
- [x] タイムラインをデフォルト非表示に
- [x] タイムラインをコメントボタンから出し入れ
- [x] 時間をタイムラインが開いているときは非表示に
- [x] タイトルと時間をタイムラインにも表示

ボード画面
- [x] 時間を拡大表示
- [x] リアクションテンプレートを非表示に
- [x] メンバー一覧を非表示に
- [x] メンバー招待を非表示に
- [x] タイトルの幅を調整
- [x] 時間の上の幅を調整
- [x] コンテナの幅を調整
- [x] アジェンダ追加ボタンと文言の色を変える？または、文言の背景色をつける

カード詳細画面
- [x] レイアウト調整
- [x] 編集完了ボタンがカラーピッカーのチェックと似ていて分かりにくい

実機操作での改善事項
- [x] 音声認識がピコピコ言って邪魔
- [x] タイムラインの出し入れが遅い
- [x] キーボードが出て画面がリレイアウトされるまでが遅い
- [x] 計測を終了してもハイライトが消えない
- [x] 最初の利用説明ガイドが見づらい
- [x] メニューの出し入れが遅い
- [x] タイトルや時間のsticky headerの描画の切り替わりが遅い
- [x] sticky headerの切り替わりのぎりぎりのところでスクロールを止めると、無限にちらつく
- [x] カード詳細を開いた後に閉じるボタンが出てこない
- [x] テキストが改行されずに投稿されてしまう
- [x] カードのドラッグ&ドロップがスムーズに動かない
- [x] アジェンダスクロールしようとした際にドラッグ＆ドロップが動いて見た目がよくない
- [x] タイムラインのドラッグをオフにすると、カードが連続してドロップできなくなった
- [x] コンテナのドラッグをオフにすると、ドロップした際にデータが表示されない
- [x] 時間のプラスマイナスボタンをデフォルトで表示しておく
- [ ] ブラウザバックの際に毎回リロードするのが邪魔 #201 で対応する
- [ ] iphone6だとまだかなり遅い #213 で対応する
- [x] iphone6だと幅が少し足りない。

全体的に描画が遅い。まずは音声認識やgrid-boardのレイアウトなどの重たい処理を外してみて様子を見るか。
→レイアウトの処理を取っ払うとかなり表示が改善されたが、やはりかなり遅い。実用を考えるとネイティブアプリの開発が必要かもしれない。

**Comment by Akira-Isegawa** [comment]
改善事項は多々残ったが、見るのもうまくできない現状よりは格段によくなったので、一旦リリースできるようにしよう。
https://github.com/minmeeting/Documents/issues/213
